version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
  
  webapp:
    container_name: webapp
    build: https://github.com/Lutfee/Flask-Practical.git
    ports:
      - "5000"
  repo-image:
    build: https://github.com/Lutfee/Flask-Practical.git
    image: repo-image
    ports:
      - 8000
  SonarQube:
    image: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: 2001369
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartesrt
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  postgresql:
  postgresql_data:
  jenkins_data:
    driver: local